[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
leptos = { workspace = true }
wasm-bindgen = { workspace = true }
fixture-scraper = { workspace = true }